---
apiVersion: v1
kind: Service
metadata:
  name: samba-ad-dc-dev
spec:
  type: ClusterIP
  clusterIP: 10.96.0.53
  selector:
    app: samba-ad-dc-dev
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 6053
      targetPort: 53
    - name: ldap
      protocol: TCP
      port: 6389
      targetPort: ldap
    - name: ldaps
      protocol: TCP
      port: 6636
      targetPort: ldaps
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: samba-ad-dc-dev
spec:
  selector:
    matchLabels:
      app: samba-ad-dc-dev
  serviceName: samba-ad-dc-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: samba-ad-dc-dev
      annotations:
        k8s.v1.cni.cncf.io/networks: samba-ad-dc-static-ip-conf
    spec:
      containers:
        - image: opensourcery/samba-ad-dc:4
          imagePullPolicy: Always
          name: samba-ad-dc-dev
          env:
            - name: SAMBA_DOMAIN
              value: SAMDOM
            - name: SAMBA_REALM
              value: SAMDOM.EXAMPLE.COM
            - name: SAMBA_DOMAIN_PASSWORD
              value: Admin100500+
            - name: NET_DEV
              value: eth0
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
            - containerPort: 389
              name: ldap
            - containerPort: 88
              name: kerberos
            - containerPort: 135
              name: epmap
            - containerPort: 139
              name: netbios-ssn
            - containerPort: 138
              name: netbios-dgm
            - containerPort: 445
              name: microsoft-ds
            - containerPort: 464
              name: kpasswd
            - containerPort: 636
              name: ldaps
            - containerPort: 3268
              name: ldp-glob-catalo
            - containerPort: 3269
              name: ldps-glob-cata
          #          lifecycle:
          #            postStart:
          #              exec:
          #                command:
          #                  - sed -i -e '/bind interfaces only = Yes/a ldap server require strong auth =no' /etc/samba/smb.conf
          securityContext:
            privileged: true
          # Assuming you want to persist the important things between pods, you should define the following
          # and possibly some PersistentVolumeClaims depending on your environment
          volumeMounts:
            - name: samba-ad-dc-var-lib
              mountPath: /var/lib/samba
            - name: samba-ad-dc-etc
              mountPath: /etc/samba
      volumes:
        - name: samba-ad-dc-var-lib
          persistentVolumeClaim:
            claimName: samba-ad-dc-var-lib-pvc
        - name: samba-ad-dc-etc
          persistentVolumeClaim:
            claimName: samba-ad-dc-etc-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: samba-ad-dc-etc-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: samba-ad-dc-var-lib-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi
