name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: upgrade-samba-ad-dc
      run: |
        docker build . --tag ghcr.io/geliotropv/upgrade-samba-ad-dc:latest
        docker run ghcr.io/geliotropv/upgrade-samba-ad-dc:latest
        docker push ghcr.io/geliotropv/upgrade-samba-ad-dc:latest
